version: '3.8'
services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app'
  server:
    build: ./
    ports:
      - '5000:5000'
    volumes:
      - './:/app'
